### ISSUE TITLE
 FaceDownPressed/FaceDownReleased processing incorrectly

### ISSUE THREAD

**Issue by ConnorTilley** [jeremymccarty/InputManagerModule#1]
If you have more than one controller plugged in, and you press (for example) face down one on controller, you'll start getting pressed and released events firing every tick. If you press face down on both controllers, the events stop firing every tick. I suspect something relating to how you detect pressed/released is bleeding between controllers. You can reproduce it yourself in your demo if you use this player controller. https://pastebin.com/DF4ELbK2

**Comment by jeremymccarty** [comment]
Pushed a fix in [Release v1.6](https://github.com/jeremymccarty/InputManagerModule/releases/tag/v1.6)
